@extends('layouts.app')
@section('title', 'Transaksi')
@section('content')
<div class="page-head"><div><h1>Riwayat transaksi</h1><p>Seluruh transaksi kasir cabang {{ $activeStore->name }}.</p></div><a class="btn btn-primary" href="{{ route('pos') }}"><i class="bi bi-plus-circle"></i> Transaksi baru</a></div>
<div class="card card-pad"><div class="card-title"><div><h2>{{ $transactions->total() }} transaksi</h2><p>Data yang dihapus tetap tersimpan sebagai arsip</p></div><div class="search" style="max-width:280px"><input placeholder="Cari invoice…" oninput="filterTransactions(this.value)"></div></div>
<div class="table-wrap"><table id="trx-table"><thead><tr><th>Invoice</th><th>Waktu</th><th>Pesanan</th><th>Kasir / member</th><th>Pembayaran</th><th>Total</th><th>Aksi</th></tr></thead><tbody>
@forelse($transactions as $trx)<tr><td class="cell-main">{{ $trx->invoice_no }}</td><td><div>{{ $trx->transacted_at->format('d M Y') }}</div><div class="cell-sub">{{ $trx->transacted_at->format('H:i') }}</div></td><td><div class="cell-main">{{ match($trx->service_type) {'takeaway' => 'Take away', 'online' => 'Ojek online', default => 'Dine in'} }}</div><div class="cell-sub">{{ $trx->service_type === 'dine_in' ? 'Meja '.($trx->table_number ?: '—') : ($trx->service_type === 'online' ? ($trx->online_platform ?: 'Platform online') : 'Dibawa pulang') }}</div></td><td><div>{{ $trx->user->name }}</div><div class="cell-sub">{{ $trx->member?->name ?? 'Pelanggan umum' }}</div></td><td><span class="badge gray">{{ strtoupper($trx->payment_method) }}</span></td><td class="money">Rp {{ number_format($trx->total,0,',','.') }}</td><td><div class="actions"><a class="btn btn-outline btn-sm" href="{{ route('transactions.print',$trx) }}" target="_blank"><i class="bi bi-printer"></i> Cetak</a>@if(in_array(auth()->user()->role, ['superadmin','owner','admin']))<form method="POST" action="{{ route('transactions.destroy',$trx) }}" onsubmit="return confirm('Arsipkan transaksi ini? Stok tidak akan berubah.')">@csrf @method('DELETE')<button class="btn btn-danger btn-sm"><i class="bi bi-archive"></i></button></form>@endif</div></td></tr>
@empty<tr><td colspan="7"><div class="cart-empty">Belum ada transaksi.</div></td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $transactions->links() }}</div></div>
@endsection
@push('scripts')<script>function filterTransactions(q){document.querySelectorAll('#trx-table tbody tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q.toLowerCase())?'':'none')}</script>@endpush
