@extends('layouts.app')
@section('title', 'Pembelian')
@section('content')
<div class="page-head"><div><h1>Pembelian stok</h1><p>Status penerimaan dan pembayaran bisa diubah langsung; stok hanya bertambah saat diterima.</p></div><button class="btn btn-primary" onclick="openModal('purchase-modal')"><i class="bi bi-bag-plus"></i> Catat pembelian</button></div>
<div class="card card-pad"><div class="card-title"><div><h2>Riwayat pembelian</h2><p>Cabang {{ $activeStore->name }}</p></div></div><div class="table-wrap"><table><thead><tr><th>No. / tanggal</th><th>Supplier</th><th>Item</th><th>Qty</th><th>Satuan</th><th>Total</th><th>Status live edit</th><th></th></tr></thead><tbody>
@forelse($purchases as $purchase)@php($item=$purchase->items->first())<tr><td><div class="cell-main">{{ $purchase->purchase_no }}</div><div class="cell-sub">{{ $purchase->purchased_at->format('d M Y') }}</div></td><td>{{ $purchase->supplier_name }}</td><td>{{ $item?->product_name }}</td><td class="money">{{ $item?->quantity }}</td><td>{{ $item?->product?->unit ?? 'unit' }}</td><td class="money">Rp {{ number_format($purchase->total,0,',','.') }}</td><td><form method="POST" action="{{ route('purchases.status',$purchase) }}" class="purchase-live-form">@csrf @method('PATCH')<select name="status" onchange="this.form.requestSubmit()"><option value="received" @selected($purchase->status==='received')>Diterima</option><option value="not_received" @selected($purchase->status!=='received')>Belum diterima</option></select><select name="payment_status" onchange="toggleDp(this.form);this.form.requestSubmit()"><option value="paid" @selected($purchase->payment_status==='paid')>Lunas</option><option value="dp" @selected($purchase->payment_status==='dp')>DP</option><option value="unpaid" @selected($purchase->payment_status==='unpaid')>Belum dibayar</option></select><input name="dp_amount" type="text" data-money-input data-min="0" value="{{ number_format($purchase->dp_amount,0,',','.') }}" style="width:110px;{{ $purchase->payment_status==='dp'?'':'display:none' }}" onchange="this.form.requestSubmit()"></form></td><td><button class="btn btn-outline btn-sm edit-purchase" data-url="{{ route('purchases.update',$purchase) }}" data-purchase="{{ json_encode(['supplier_name'=>$purchase->supplier_name,'product_id'=>$item?->product_id,'quantity'=>$item?->quantity,'unit_cost'=>$item?->unit_cost,'purchased_at'=>$purchase->purchased_at->format('Y-m-d'),'status'=>$purchase->status==='received'?'received':'not_received','payment_status'=>$purchase->payment_status,'dp_amount'=>$purchase->dp_amount,'notes'=>$purchase->notes]) }}"><i class="bi bi-pencil"></i> Koreksi</button></td></tr>
@empty<tr><td colspan="8"><div class="cart-empty">Belum ada pembelian.</div></td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $purchases->links() }}</div></div>
@endsection
@push('modals')
<div class="modal" id="purchase-modal"><div class="modal-card"><div class="modal-head"><div><h2>Catat pembelian</h2><div class="hint">Pilih “belum diterima” bila barang masih dalam pengiriman.</div></div><button class="modal-close" onclick="closeModal('purchase-modal')">×</button></div><form method="POST" action="{{ route('purchases.store') }}" class="form-grid">@csrf<div class="field full"><label>Supplier</label><input name="supplier_name" required></div><div class="field full"><label>Produk</label><select name="product_id" required>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} · {{ $product->unit }}</option>@endforeach</select></div><div class="field"><label>Qty</label><input type="number" name="quantity" min="1" required></div><div class="field"><label>Harga beli / satuan</label><input type="text" name="unit_cost" data-money-input data-min="0" inputmode="numeric" required></div><div class="field"><label>Status barang</label><select name="status"><option value="received">Diterima</option><option value="not_received">Belum diterima</option></select></div><div class="field"><label>Status pembayaran</label><select name="payment_status" id="new-payment-status" onchange="document.getElementById('new-dp').hidden=this.value!=='dp'"><option value="paid">Lunas</option><option value="dp">DP</option><option value="unpaid">Belum dibayar</option></select></div><div class="field" id="new-dp" hidden><label>Nominal DP</label><input type="text" name="dp_amount" data-money-input data-min="0" inputmode="numeric"></div><div class="field"><label>Tanggal pembelian</label><input type="date" name="purchased_at" value="{{ now()->toDateString() }}" required></div><div class="field full"><label>Catatan</label><input name="notes"></div><div class="field full"><button class="btn btn-primary">Simpan pembelian</button></div></form></div></div>
<div class="modal" id="edit-purchase-modal"><div class="modal-card"><div class="modal-head"><div><h2>Koreksi pembelian</h2><div class="hint">Koreksi jumlah memperbarui selisih stok. Perubahan supplier, harga, atau catatan tidak mengubah stok.</div></div><button class="modal-close" onclick="closeModal('edit-purchase-modal')">×</button></div><form method="POST" id="edit-purchase-form" class="form-grid">@csrf @method('PUT')<div class="field full"><label>Supplier</label><input name="supplier_name" required></div><div class="field full"><label>Produk</label><select name="product_id" required>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} · {{ $product->unit }}</option>@endforeach</select></div><div class="field"><label>Qty</label><input type="number" step="0.001" name="quantity" min="0.001" required></div><div class="field"><label>Harga beli / satuan</label><input type="text" name="unit_cost" data-money-input data-min="0" required></div><div class="field"><label>Status barang</label><select name="status"><option value="received">Diterima</option><option value="not_received">Belum diterima</option></select></div><div class="field"><label>Status pembayaran</label><select name="payment_status"><option value="paid">Lunas</option><option value="dp">DP</option><option value="unpaid">Belum dibayar</option></select></div><div class="field"><label>Nominal DP</label><input type="text" name="dp_amount" data-money-input data-min="0"></div><div class="field"><label>Tanggal</label><input type="date" name="purchased_at" required></div><div class="field full"><label>Catatan</label><input name="notes"></div><div class="field full"><button class="btn btn-primary">Simpan koreksi</button></div></form></div></div>
@endpush
@push('scripts')<script>function toggleDp(form){form.querySelector('[name=dp_amount]').style.display=form.payment_status.value==='dp'?'':'none'}document.querySelectorAll('.edit-purchase').forEach(button=>button.addEventListener('click',()=>{const form=document.getElementById('edit-purchase-form'),data=JSON.parse(button.dataset.purchase);form.action=button.dataset.url;Object.entries(data).forEach(([key,value])=>{const input=form.elements[key];if(input)input.value=value??''});['unit_cost','dp_amount'].forEach(key=>setMoneyInputValue(form.elements[key],Number(data[key]||0)));openModal('edit-purchase-modal')}));</script>@endpush
