@extends('layouts.app')
@section('title', 'Pengeluaran')
@section('content')
<div class="page-head"><div><h1>Pengeluaran operasional</h1><p>Catat seluruh biaya operasional warung secara lengkap.</p></div><button class="btn btn-primary" onclick="openModal('expense-modal')"><i class="bi bi-wallet2"></i> Catat pengeluaran</button></div>
<div class="card card-pad"><div class="card-title"><div><h2>Riwayat pengeluaran</h2><p>{{ $expenses->total() }} catatan</p></div></div><div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Keterangan</th><th>Kategori</th><th>Dibayar via</th><th>Nominal</th><th></th></tr></thead><tbody>
@forelse($expenses as $expense)<tr><td>{{ $expense->expense_date->format('d M Y') }}</td><td class="cell-main">{{ $expense->description }}</td><td><span class="badge gray">{{ $expense->category }}</span></td><td>{{ strtoupper($expense->payment_method ?? 'cash') }}</td><td class="money">Rp {{ number_format($expense->amount,0,',','.') }}</td><td><div class="actions"><button type="button" class="btn btn-outline btn-sm edit-expense" data-url="{{ route('expenses.update',$expense) }}" data-expense="{{ json_encode(['category'=>$expense->category,'expense_date'=>$expense->expense_date->format('Y-m-d'),'payment_method'=>$expense->payment_method ?? 'cash','description'=>$expense->description,'amount'=>(float)$expense->amount]) }}"><i class="bi bi-pencil"></i> Edit</button><form method="POST" action="{{ route('expenses.destroy',$expense) }}" onsubmit="return confirm('Hapus pengeluaran ini? Data tetap disimpan di arsip audit.')">@csrf @method('DELETE')<button class="btn btn-danger btn-sm"><i class="bi bi-trash"></i> Hapus</button></form></div></td></tr>@empty<tr><td colspan="6"><div class="cart-empty">Belum ada pengeluaran.</div></td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $expenses->links() }}</div></div>
@endsection
@push('modals')
<div class="modal" id="expense-modal"><div class="modal-card"><div class="modal-head"><h2>Catat pengeluaran</h2><button class="modal-close" onclick="closeModal('expense-modal')">×</button></div><form method="POST" action="{{ route('expenses.store') }}" class="form-grid">@csrf
<div class="field"><label>Kategori</label><select name="category" required>@foreach($categories as $category)<option value="{{ $category }}">{{ $category }}</option>@endforeach</select></div><div class="field"><label>Tanggal</label><input type="date" name="expense_date" value="{{ now()->toDateString() }}" required></div>
<div class="field full"><label>Dibayar melalui</label><select name="payment_method" required><option value="cash">Tunai</option><option value="transfer">Transfer</option><option value="qris">QRIS</option><option value="debit">Kartu debit</option></select></div>
<div class="field full"><label>Keterangan</label><input name="description" required placeholder="Contoh: Belanja gas dapur"></div><div class="field full"><label>Nominal</label><input type="text" name="amount" data-money-input data-min="1" inputmode="numeric" autocomplete="off" placeholder="0" required></div>
<div class="field full"><button class="btn btn-primary">Simpan pengeluaran</button></div></form></div></div>
<div class="modal" id="edit-expense-modal"><div class="modal-card"><div class="modal-head"><h2>Edit pengeluaran</h2><button class="modal-close" onclick="closeModal('edit-expense-modal')">×</button></div><form method="POST" id="edit-expense-form" class="form-grid">@csrf @method('PUT')
<div class="field"><label>Kategori</label><select name="category" required>@foreach($categories as $category)<option value="{{ $category }}">{{ $category }}</option>@endforeach</select></div><div class="field"><label>Tanggal</label><input type="date" name="expense_date" required></div>
<div class="field full"><label>Dibayar melalui</label><select name="payment_method" required><option value="cash">Tunai</option><option value="transfer">Transfer</option><option value="qris">QRIS</option><option value="debit">Kartu debit</option></select></div>
<div class="field full"><label>Keterangan</label><input name="description" required></div><div class="field full"><label>Nominal</label><input type="text" name="amount" data-money-input data-min="1" inputmode="numeric" autocomplete="off" required></div>
<div class="field full"><button class="btn btn-primary">Simpan perubahan</button></div></form></div></div>
@endpush
@push('scripts')<script>document.querySelectorAll('.edit-expense').forEach(button=>button.addEventListener('click',()=>{const form=document.getElementById('edit-expense-form'),data=JSON.parse(button.dataset.expense);form.action=button.dataset.url;Object.entries(data).forEach(([key,value])=>{const input=form.elements[key];if(input)input.value=value??''});setMoneyInputValue(form.elements.amount,Number(data.amount||0));openModal('edit-expense-modal')}));</script>@endpush
