@extends('layouts.app')
@section('title', 'Produk')
@section('content')
<div class="page-head"><div><h1>Daftar produk</h1><p>Harga normal dan online dipilih otomatis berdasarkan jenis pesanan.</p></div><div class="actions"><a class="btn btn-outline" href="{{ route('products.export') }}"><i class="bi bi-file-earmark-arrow-down"></i> Download Excel</a><button class="btn btn-soft" onclick="openModal('import-modal')"><i class="bi bi-file-earmark-arrow-up"></i> Import Excel</button><button class="btn btn-primary" onclick="openModal('product-modal')"><i class="bi bi-plus-circle"></i> Tambah produk</button></div></div>
<div class="card card-pad"><div class="card-title"><div><h2>{{ $products->total() }} produk</h2><p>Stok mengikuti cabang aktif</p></div><div class="search" style="max-width:280px"><input placeholder="Cari produk…" oninput="filterRows(this.value)"></div></div><div class="table-wrap"><table id="product-table"><thead><tr><th>Produk</th><th>Jenis</th><th>Kategori</th><th>Harga beli</th><th>Harga normal</th><th>Harga online</th><th>Stok / batas aman</th><th></th></tr></thead><tbody>
@forelse($products as $product)
@php($currentStock=$product->product_type==='menu'?($product->daily_stock??0):($product->warehouse_stock??0))
<tr><td><div class="cell-main">{{ $product->name }}</div><div class="cell-sub">{{ $product->sku }} · {{ $product->barcode ?: 'Tanpa barcode' }}</div></td><td><span class="badge {{ $product->product_type==='ingredient'?'amber':'' }}">{{ $product->product_type==='menu'?'Menu harian':'Bahan baku' }}</span></td><td><span class="badge gray">{{ $product->category?->name ?? 'Umum' }}</span></td><td>Rp {{ number_format($product->purchase_price,0,',','.') }}</td><td class="money">{{ $product->product_type==='menu'?'Rp '.number_format($product->selling_price,0,',','.'):'—' }}</td><td class="money">{{ $product->product_type==='menu'?'Rp '.number_format($product->online_selling_price ?: $product->selling_price,0,',','.'):'—' }}</td><td><span class="badge {{ $currentStock<=$product->minimum_stock?'amber':'' }}">{{ $currentStock }} / min. {{ $product->minimum_stock }} {{ $product->unit }}</span></td><td><div class="actions"><button class="btn btn-outline btn-sm edit-product" data-id="{{ $product->id }}" data-name="{{ $product->name }}" data-sku="{{ $product->sku }}" data-barcode="{{ $product->barcode }}" data-category="{{ $product->category_id }}" data-unit="{{ $product->unit }}" data-buy="{{ $product->purchase_price }}" data-sell="{{ $product->selling_price }}" data-online="{{ $product->online_selling_price }}" data-minimum="{{ $product->minimum_stock }}"><i class="bi bi-pencil"></i> Edit</button><form method="POST" action="{{ route('products.destroy',$product) }}" onsubmit="return confirm('Arsipkan produk ini?')">@csrf @method('DELETE')<button class="btn btn-danger btn-sm"><i class="bi bi-archive"></i></button></form></div></td></tr>
@empty<tr><td colspan="8"><div class="cart-empty">Belum ada produk.</div></td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $products->links() }}</div></div>
@endsection
@push('modals')
<div class="modal" id="product-modal"><div class="modal-card"><div class="modal-head"><div><h2>Tambah produk</h2><div class="hint">Stok minimum menentukan status Aman / Perlu perhatian / Tidak aman.</div></div><button class="modal-close" onclick="closeModal('product-modal')">×</button></div><form method="POST" action="{{ route('products.store') }}" class="form-grid">@csrf<div class="field full"><label>Nama produk</label><input name="name" required></div><div class="field full"><label>Jenis</label><select name="product_type" required><option value="menu">Menu siap jual · stok harian</option><option value="ingredient">Bahan baku · stok gudang</option></select></div><div class="field"><label>SKU</label><input name="sku" required></div><div class="field"><label>Barcode</label><input name="barcode"></div><div class="field"><label>Kategori</label><select name="category_id"><option value="">Umum</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div class="field"><label>Satuan</label><input name="unit" value="pcs" required></div><div class="field"><label>Harga beli</label><input type="text" name="purchase_price" data-money-input data-min="0" inputmode="numeric" required></div><div class="field"><label>Harga normal</label><input type="text" name="selling_price" data-money-input data-min="0" inputmode="numeric" required></div><div class="field"><label>Harga online</label><input type="text" name="online_selling_price" data-money-input data-min="0" inputmode="numeric"></div><div class="field"><label>Stok awal</label><input type="number" name="initial_stock" value="0" min="0"></div><div class="field"><label>Stok minimum</label><input type="number" name="minimum_stock" value="5" min="0" required></div><div class="field full"><button class="btn btn-primary">Simpan produk</button></div></form></div></div>
<div class="modal" id="edit-product-modal"><div class="modal-card"><div class="modal-head"><h2>Edit produk</h2><button class="modal-close" onclick="closeModal('edit-product-modal')">×</button></div><form method="POST" id="edit-product-form" class="form-grid">@csrf @method('PUT')<div class="field full"><label>Nama</label><input id="edit-name" name="name" required></div><div class="field"><label>SKU</label><input id="edit-sku" name="sku" required></div><div class="field"><label>Barcode</label><input id="edit-barcode" name="barcode"></div><div class="field"><label>Kategori</label><select id="edit-category" name="category_id"><option value="">Umum</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div><div class="field"><label>Satuan</label><input id="edit-unit" name="unit" required></div><div class="field"><label>Harga beli</label><input id="edit-buy" type="text" name="purchase_price" data-money-input data-min="0" inputmode="numeric" required></div><div class="field"><label>Harga normal</label><input id="edit-sell" type="text" name="selling_price" data-money-input data-min="0" inputmode="numeric" required></div><div class="field"><label>Harga online</label><input id="edit-online" type="text" name="online_selling_price" data-money-input data-min="0" inputmode="numeric"></div><div class="field"><label>Stok minimum</label><input id="edit-minimum" type="number" name="minimum_stock" min="0" required></div><div class="field full"><button class="btn btn-primary">Simpan perubahan</button></div></form></div></div>
<div class="modal" id="import-modal"><div class="modal-card" style="max-width:480px"><div class="modal-head"><div><h2>Import produk dari Excel</h2><div class="hint">Gunakan hasil Download Excel sebagai template paling aman.</div></div><button class="modal-close" onclick="closeModal('import-modal')">×</button></div><form method="POST" action="{{ route('products.import') }}" enctype="multipart/form-data" class="form-grid">@csrf<div class="field full"><label>File .xlsx / .xls / .csv</label><input type="file" name="file" accept=".xlsx,.xls,.csv" required></div><div class="field full"><button class="btn btn-primary">Import & perbarui</button></div></form></div></div>
@endpush
@push('scripts')<script>function filterRows(q){document.querySelectorAll('#product-table tbody tr').forEach(r=>r.style.display=r.innerText.toLowerCase().includes(q.toLowerCase())?'':'none')}document.querySelectorAll('.edit-product').forEach(button=>button.addEventListener('click',()=>{const d=button.dataset;document.getElementById('edit-product-form').action='/produk/'+d.id;['name','sku','barcode','unit','buy','sell','online','minimum','category'].forEach(k=>document.getElementById('edit-'+k).value=d[k]||'');['buy','sell','online'].forEach(k=>setMoneyInputValue(document.getElementById('edit-'+k),d[k]));openModal('edit-product-modal')}));</script>@endpush
