@extends('layouts.app')
@section('title', 'Pengaturan')
@section('content')
<div class="page-head"><div><h1>Pengaturan sistem</h1><p>Pengaturan bertanda cabang aktif hanya berlaku untuk <b>{{ $settingsStore->name }}</b>.</p></div><span class="badge"><i class="bi bi-geo-alt"></i> {{ $settingsStore->name }}</span></div>
<section class="card card-pad" id="aturan-bisnis" style="margin-bottom:16px;border:2px solid var(--primary,#476c5c)"><div class="card-title"><div><h2><i class="bi bi-sliders"></i> Aturan laporan & membership</h2><p>Khusus {{ $settingsStore->name }}: persentase laporan non-riil dan diskon otomatis member baru.</p></div><span class="badge">Per cabang</span></div><form method="POST" action="{{ route('settings.business-rules') }}" class="form-grid">@csrf<input type="hidden" name="store_id" value="{{ $settingsStore->id }}"><div class="field"><label>Persentase laporan non-riil</label><div style="display:flex;align-items:center;gap:8px"><input type="number" name="non_real_percentage" min="0" max="100" step="0.01" value="{{ $settingsStore->non_real_percentage }}" required><b>% dari laporan riil</b></div><small class="hint">Contoh 50%: nilai laporan non-riil menjadi setengah laporan riil.</small></div><div class="field"><label>Diskon default membership</label><div style="display:flex;align-items:center;gap:8px"><input type="number" name="member_discount_percent" min="0" max="100" step="0.1" value="{{ $settingsStore->member_discount_percent }}" required><b>%</b></div><small class="hint">Dipakai saat kartu baru diaktifkan di cabang ini; masih dapat disesuaikan per member.</small></div><div class="field full"><button class="btn btn-primary"><i class="bi bi-check2-circle"></i> Simpan untuk {{ $settingsStore->name }}</button></div></form></section>
<div class="grid two-col"><section class="card card-pad"><div class="card-title"><div><h2>Identitas warung</h2><p>Nama dan logo aplikasi/struk khusus {{ $settingsStore->name }}</p></div><span class="badge">Per cabang</span></div><form method="POST" action="{{ route('settings.brand') }}" enctype="multipart/form-data" class="form-grid">@csrf<input type="hidden" name="store_id" value="{{ $settingsStore->id }}"><div class="field full"><label>Nama usaha</label><input name="business_name" value="{{ $settingsStore->brandName() }}" required></div><div class="field full"><label>Logo</label><input type="file" name="logo" accept="image/*">@if($settingsStore->logo_path)<small class="hint">Logo cabang sudah tersimpan. Pilih file baru untuk mengganti.</small>@endif</div><div class="field full"><button class="btn btn-primary">Simpan untuk {{ $settingsStore->name }}</button></div></form></section>
<section class="card card-pad"><div class="card-title"><div><h2>Tampilan struk</h2><p>Berlaku pada struk transaksi {{ $settingsStore->name }}</p></div><span class="badge">Per cabang</span></div><form method="POST" action="{{ route('settings.receipt') }}" class="form-grid">@csrf<input type="hidden" name="store_id" value="{{ $settingsStore->id }}"><div class="field full"><label>Header tambahan</label><input name="receipt_header" value="{{ $settingsStore->receipt_header }}" placeholder="Contoh: Sejak 1998"></div><div class="field full"><label>Footer struk</label><input name="receipt_footer" value="{{ $settingsStore->receipt_footer }}" placeholder="Terima kasih"></div><div class="field"><label class="inventory-note"><input type="checkbox" name="receipt_show_logo" value="1" @checked($settingsStore->receipt_show_logo) style="width:auto;min-height:auto"><span>Tampilkan logo</span></label></div><div class="field"><label class="inventory-note"><input type="checkbox" name="receipt_sort_by_category" value="1" @checked($settingsStore->receipt_sort_by_category) style="width:auto;min-height:auto"><span>Urutkan item per kategori</span></label></div><div class="field full"><button class="btn btn-primary">Simpan untuk {{ $settingsStore->name }}</button></div></form></section></div>
<div class="grid two-col" style="margin-top:16px"><section class="card card-pad"><div class="card-title"><div><h2>Perangkat terhubung</h2><p>Printer, scanner, cash drawer, atau display</p></div><button class="btn btn-soft btn-sm" onclick="openModal('device-modal')">Tambah</button></div><div class="list">@forelse($devices as $device)<div class="list-item"><span class="list-icon"><i class="bi bi-usb-symbol"></i></span><div class="list-body"><div class="list-title">{{ $device->name }}</div><div class="list-sub">{{ str_replace('_',' ',$device->type) }} · {{ $device->connection ?: 'Otomatis' }} · {{ $device->store?->name ?? 'Semua cabang' }}</div></div><form method="POST" action="{{ route('settings.device.destroy',$device) }}">@csrf @method('DELETE')<button class="btn btn-danger btn-sm"><i class="bi bi-x"></i></button></form></div>@empty<div class="cart-empty">Belum ada perangkat.</div>@endforelse</div></section><section class="card card-pad"><div class="card-title"><div><h2>Kartu member pra-cetak</h2><p>Buat QR sekarang, aktivasi saat customer mendaftar</p></div></div>@if(auth()->user()->role===\App\Models\User::SUPERADMIN)<form method="POST" action="{{ route('settings.member-card') }}" class="actions" style="margin-bottom:12px">@csrf<input type="number" name="count" min="1" max="100" value="10" style="width:90px"><button class="btn btn-primary">Buat batch QR</button></form>@endif<div class="list">@forelse($cards as $card)<button type="button" class="list-item card-print-trigger" data-code="{{ $card->member_code }}" data-qr="{{ $card->qr_code }}" style="border:0;width:100%;text-align:left"><span class="list-icon"><i class="bi bi-qr-code"></i></span><span class="list-body"><b>{{ $card->member_code }}</b><small>Belum diaktivasi · klik untuk cetak</small></span></button>@empty<div class="cart-empty">Belum ada kartu siap pakai.</div>@endforelse</div></section></div>
@php($moduleList = \App\Models\Role::MODULES)
<section class="card card-pad" id="master-role" style="margin-top:16px"><div class="card-title"><div><h2>Master role & hak akses menu</h2><p>Centang menu yang boleh dibuka tiap role. Perubahan langsung berlaku pada permintaan berikutnya.</p></div>@if($canManageRoles)<button class="btn btn-primary" onclick="openModal('role-modal')"><i class="bi bi-plus-circle"></i> Tambah role</button>@endif</div>
<div class="table-wrap"><table class="role-matrix"><thead><tr><th>Role</th>@foreach($moduleList as $moduleKey=>$moduleLabel)<th class="role-matrix-module"><span>{{ $moduleLabel }}</span></th>@endforeach<th class="role-matrix-module"><span>Non-riil</span></th><th class="role-matrix-module"><span>PIN otorisasi</span></th><th>Akun</th><th></th></tr></thead><tbody>
@foreach($roles as $role)
@php($usedBy = $userCountPerRole[$role->key] ?? 0)
@if($canManageRoles && !$role->is_system)<form method="POST" action="{{ route('settings.role.update',$role) }}" id="role-form-{{ $role->id }}">@csrf @method('PUT')<input type="hidden" name="name" value="{{ $role->name }}"><input type="hidden" name="summary" value="{{ $role->summary }}"></form>@endif
<tr>
<td><div class="cell-main">{{ $role->name }}</div><div class="cell-sub">{{ $role->key }}@if($role->is_system) · <span class="badge">sistem</span>@endif</div><div class="cell-sub">{{ $role->can_access_all_stores ? 'Semua warung' : 'Cabang sendiri' }}</div></td>
@foreach($moduleList as $moduleKey=>$moduleLabel)
<td class="role-matrix-cell"><input type="checkbox" form="role-form-{{ $role->id }}" name="modules[]" value="{{ $moduleKey }}" @checked($role->canAccess($moduleKey)) @disabled($role->is_system || !$canManageRoles) aria-label="{{ $role->name }} · {{ $moduleLabel }}"></td>
@endforeach
<td class="role-matrix-cell"><input type="checkbox" form="role-form-{{ $role->id }}" name="can_see_non_real" value="1" @checked($role->can_see_non_real) @disabled($role->is_system || !$canManageRoles) aria-label="{{ $role->name }} boleh laporan non-riil"></td>
<td class="role-matrix-cell"><input type="checkbox" form="role-form-{{ $role->id }}" name="is_supervisor" value="1" @checked($role->is_supervisor) @disabled($role->is_system || !$canManageRoles) aria-label="{{ $role->name }} pemegang PIN otorisasi"></td>
<td class="money">{{ $usedBy }}</td>
<td><div class="actions">@if($canManageRoles && !$role->is_system)<button class="btn btn-primary btn-sm" form="role-form-{{ $role->id }}"><i class="bi bi-check2"></i> Simpan</button>@if($usedBy===0)<form method="POST" action="{{ route('settings.role.destroy',$role) }}" onsubmit="return confirm('Hapus role {{ $role->name }}?')">@csrf @method('DELETE')<button class="btn btn-danger btn-sm" title="Hapus role"><i class="bi bi-trash"></i></button></form>@endif @endif</div></td>
</tr>
@endforeach
</tbody></table></div>
<p class="hint" style="margin-top:10px"><i class="bi bi-info-circle"></i> Superadmin adalah role sistem sehingga hak aksesnya terkunci. Akses lintas warung tidak diatur di sini — hanya Superadmin dan Head of Ops yang boleh melihat warung lain.</p></section>
<section class="card card-pad" style="margin-top:16px"><div class="card-title"><div><h2>Tiering akses & akun</h2><p>Hanya Superadmin dapat membuat atau menghapus akun level bawah.</p></div>@if($creatableRoles)<button class="btn btn-primary" onclick="openModal('user-modal')">Tambah akun</button>@endif</div><div class="table-wrap"><table><thead><tr><th>Pengguna</th><th>Role</th><th>Cabang</th><th>Akses utama</th><th></th></tr></thead><tbody>@foreach($users as $user)<tr><td><div class="cell-main">{{ $user->name }}</div><div class="cell-sub">{{ $user->email }}</div></td><td><span class="badge">{{ $user->roleLabel() }}</span></td><td>{{ $user->store?->name }}</td><td class="cell-sub">{{ $user->roleDefinition()?->summary ?? 'Role sudah tidak ada di master' }}</td><td><div class="actions">@if(auth()->user()->role===\App\Models\User::SUPERADMIN&&$user->isSupervisor())<button class="btn btn-outline btn-sm pin-trigger" data-url="{{ route('settings.user.pin',$user) }}" data-name="{{ $user->name }}"><i class="bi bi-key"></i> PIN</button>@endif @if(auth()->user()->role===\App\Models\User::SUPERADMIN&&$user->id!==auth()->id())<form method="POST" action="{{ route('settings.user.destroy',$user) }}" onsubmit="return confirm('Nonaktifkan akun ini?')">@csrf @method('DELETE')<button class="btn btn-danger btn-sm"><i class="bi bi-person-x"></i></button></form>@endif</div></td></tr>@endforeach</tbody></table></div></section>
<div class="grid two-col" style="margin-top:16px"><section class="card card-pad"><div class="card-title"><div><h2>Cabang</h2><p>{{ $stores->count() }} warung aktif</p></div><button class="btn btn-soft btn-sm" onclick="openModal('branch-modal')">Tambah</button></div><div class="list">@foreach($stores as $store)<div class="list-item"><span class="list-icon"><i class="bi bi-shop"></i></span><div class="list-body"><div class="list-title">{{ $store->name }}</div><div class="list-sub">{{ $store->code }} · {{ $store->address ?: 'Alamat belum diisi' }}</div></div></div>@endforeach</div></section><section class="card card-pad"><div class="card-title"><div><h2>Pemeliharaan</h2><p>Perintah aman yang diizinkan sistem</p></div></div>@if(session('maintenance_output'))<pre class="maintenance-output">{{ session('maintenance_output') }}</pre>@endif<form method="POST" action="{{ route('settings.maintenance') }}" class="actions">@csrf<select name="command"><option value="migrate">Migrasi database</option><option value="optimize_clear">Bersihkan cache</option><option value="storage_link">Hubungkan storage</option></select><button class="btn btn-soft">Jalankan</button></form></section></div>
@endsection
@push('modals')
<div class="modal" id="device-modal"><div class="modal-card"><div class="modal-head"><h2>Tambah perangkat</h2><button class="modal-close" onclick="closeModal('device-modal')">×</button></div><form method="POST" action="{{ route('settings.device') }}" class="form-grid">@csrf<div class="field full"><label>Nama perangkat</label><input name="name" required></div><div class="field"><label>Jenis</label><select name="type"><option value="receipt_printer">Printer struk</option><option value="cash_drawer">Cash drawer</option><option value="barcode_scanner">Barcode scanner</option><option value="customer_display">Customer display</option><option value="other">Lainnya</option></select></div><div class="field"><label>Cabang</label><select name="store_id"><option value="">Semua cabang</option>@foreach($stores as $store)<option value="{{ $store->id }}" @selected($store->id===$settingsStore->id)>{{ $store->name }}</option>@endforeach</select></div><div class="field full"><label>Koneksi / alamat</label><input name="connection" placeholder="USB, Bluetooth, IP, atau nama perangkat"></div><div class="field full"><button class="btn btn-primary">Sambungkan</button></div></form></div></div>
<div class="modal" id="user-modal"><div class="modal-card"><div class="modal-head"><h2>Tambah akun</h2><button class="modal-close" onclick="closeModal('user-modal')">×</button></div><form method="POST" action="{{ route('settings.user') }}" class="form-grid">@csrf<div class="field full"><label>Nama</label><input name="name" required></div><div class="field full"><label>Email</label><input type="email" name="email" required></div><div class="field"><label>Role</label><select name="role">@foreach($creatableRoles as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div><div class="field"><label>Cabang</label><select name="store_id">@foreach($stores as $store)<option value="{{ $store->id }}">{{ $store->name }}</option>@endforeach</select></div><div class="field"><label>Password</label><input type="password" name="password" minlength="8" required></div><div class="field"><label>PIN otorisasi <small>(Manager/SPV)</small></label><input type="password" name="authorization_pin" inputmode="numeric" minlength="4" maxlength="8"></div><div class="field full"><button class="btn btn-primary">Buat akun</button></div></form></div></div>
<div class="modal" id="pin-modal"><div class="modal-card" style="max-width:420px"><div class="modal-head"><div><h2>Atur PIN otorisasi</h2><div id="pin-user-name" class="hint"></div></div><button class="modal-close" onclick="closeModal('pin-modal')">×</button></div><form id="pin-form" method="POST" class="form-grid">@csrf @method('PATCH')<div class="field full"><label>PIN baru (4–8 digit)</label><input type="password" name="authorization_pin" inputmode="numeric" minlength="4" maxlength="8" required></div><div class="field full"><button class="btn btn-primary">Simpan PIN</button></div></form></div></div>
<div class="modal" id="role-modal"><div class="modal-card"><div class="modal-head"><div><h2>Tambah role</h2><div class="hint">Pilih menu yang boleh dibuka role ini.</div></div><button class="modal-close" onclick="closeModal('role-modal')">×</button></div><form method="POST" action="{{ route('settings.role') }}" class="form-grid">@csrf<div class="field"><label>Nama role</label><input name="name" required placeholder="Contoh: Kasir Senior"></div><div class="field"><label>Kode role</label><input name="key" required pattern="[a-z][a-z0-9_]*" placeholder="kasir_senior"><small class="hint">Huruf kecil, angka, dan garis bawah.</small></div><div class="field full"><label>Keterangan singkat</label><input name="summary" placeholder="Kasir, transaksi, member"></div><div class="field full"><label>Hak akses menu</label><div class="role-module-grid">@foreach(\App\Models\Role::MODULES as $moduleKey=>$moduleLabel)<label class="inventory-note"><input type="checkbox" name="modules[]" value="{{ $moduleKey }}" style="width:auto;min-height:auto"><span>{{ $moduleLabel }}</span></label>@endforeach</div></div><div class="field"><label class="inventory-note"><input type="checkbox" name="can_see_non_real" value="1" style="width:auto;min-height:auto"><span>Boleh laporan non-riil</span></label></div><div class="field"><label class="inventory-note"><input type="checkbox" name="is_supervisor" value="1" style="width:auto;min-height:auto"><span>Pemegang PIN otorisasi</span></label></div><div class="field full"><button class="btn btn-primary">Simpan role</button></div></form></div></div>
<div class="modal" id="branch-modal"><div class="modal-card"><div class="modal-head"><h2>Tambah cabang</h2><button class="modal-close" onclick="closeModal('branch-modal')">×</button></div><form method="POST" action="{{ route('settings.branch') }}" class="form-grid">@csrf<div class="field full"><label>Nama</label><input name="name" required></div><div class="field"><label>Kode</label><input name="code" required></div><div class="field"><label>Telepon</label><input name="phone"></div><div class="field full"><label>Alamat</label><textarea name="address"></textarea></div><div class="field full"><button class="btn btn-primary">Simpan cabang</button></div></form></div></div>
<div class="modal" id="card-print-modal"><div class="modal-card" style="max-width:430px"><div class="modal-head no-print"><h2>Kartu pra-cetak</h2><button class="modal-close" onclick="closeModal('card-print-modal')">×</button></div><article class="membership-card"><div class="membership-card-head"><div class="membership-brand"><span>{{ strtoupper(substr($tenant->name,0,1)) }}</span><div><b>{{ $tenant->name }}</b><small>MEMBER CARD</small></div></div></div><div class="membership-card-body"><div class="membership-identity"><small>Aktivasi saat mendaftar</small><h3 id="pre-card-code"></h3></div><div class="membership-card-qr"><canvas id="pre-card-qr"></canvas></div></div></article><div class="actions no-print" style="justify-content:center;margin-top:12px"><button class="btn btn-primary" onclick="window.print()">Cetak kartu</button></div></div></div>
@endpush
@push('scripts')<script>document.querySelectorAll('.card-print-trigger').forEach(button=>button.addEventListener('click',async()=>{document.getElementById('pre-card-code').textContent=button.dataset.code;await renderQr(document.getElementById('pre-card-qr'),button.dataset.qr);openModal('card-print-modal')}));document.querySelectorAll('.pin-trigger').forEach(button=>button.addEventListener('click',()=>{document.getElementById('pin-form').action=button.dataset.url;document.getElementById('pin-user-name').textContent=button.dataset.name;openModal('pin-modal')}));</script>@endpush
